//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_databaseEntities : DbContext
    {
        public Project_databaseEntities()
            : base("name=Project_databaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admins { get; set; }
        public virtual DbSet<Driver> Drivers { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<Offence> Offences { get; set; }
        public virtual DbSet<Surgeon> Surgeons { get; set; }
        public virtual DbSet<Vehicle> Vehicles { get; set; }
        public virtual DbSet<Offence_info> Offence_info { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
