//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Offence_info
    {
        public int Id { get; set; }
        public Nullable<int> Driver_id { get; set; }
        public Nullable<int> Surgeon_id { get; set; }
        public Nullable<int> Offence_id { get; set; }
        public string Occuring_date { get; set; }
        public string Payment_status { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Offence Offence { get; set; }
        public virtual Surgeon Surgeon { get; set; }
    }
}
