//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        public int Id { get; set; }
        public string Model_name { get; set; }
        public string Category { get; set; }
        public int Registration_number { get; set; }
        public string Color { get; set; }
        public int Cc { get; set; }
        public int Engine_number { get; set; }
        public int Chasis_number { get; set; }
        public string Is_rent { get; set; }
        public string Issuing_authority { get; set; }
        public int Weight { get; set; }
        public string Registration_date { get; set; }
        public string Validity { get; set; }
        public int Seat_number { get; set; }
        public string Photo { get; set; }
    
        public virtual Driver Driver { get; set; }
    }
}
